[package]
name = "uvc"
description = "Safe and ergonomic wrapper around libuvc, allowing capture of webcam streams"
version = "0.1.0"
authors = ["Magnus Ulimoen <flymagnus@gmail.com>"]
license = "MIT"
repository = "https://github.com/mulimoen/libuvc-rs.git"

[dependencies]
uvc-sys = "0.1.0"

[dev-dependencies]
glium = "^0.22.0"
