[package]
name = "uvc-sys"
description = "Raw wrapper of libuvc"
version = "0.1.1"
authors = ["Magnus Ulimoen <flymagnus@gmail.com>"]
links = "uvc"
build = "build.rs"
license = "MIT"
repository = "https://github.com/mulimoen/libuvc-rs.git"
categories = ["external-ffi-bindings", "multimedia::video"]

[build-dependencies]
bindgen = "^0.37.0"
