[package]
name = "uvc-src"
version = "0.1.2"
authors = ["Magnus Ulimoen <flymagnus@gmail.com>"]
edition = "2018"
license-file = "source/LICENSE.txt"
build = "build.rs"
repository = "https://github.com/mulimoen/libuvc-rs"
description = "Vendored version of libuvc"

[dependencies]
mozjpeg-sys = { version = "0.10.4", default-features = false }

[build-dependencies]
cmake = "0.1.44"
bindgen = "0.54.0"
